[build]
  publish = "dist/open-house-fun"
  command = "ng build --prod"
  functions = "./functions"
[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
