type Property {
  address: String!
  redfinURL: String!
  askingPrice: Float!
  soldForPrice: Float!
  dateSold: Time!
  challenges: [Challenge!] @relation
}

type Challenge {
  created: Time!
  property: Property!
  group: Group!
  guesses: [Guess!] @relation
}

type Group {
  challenges: [Challenge!] @relation
  users: [User!] @relation
}

type User {
  name: String!
  groups: [Group!] @relation
  guesses: [Guess!] @relation
}

type Guess {
  price: Float!
  challenge: Challenge!
  user: User!
}
